#
# Tested on lilygo t-eth-elite[H744]
# https://lilygo.cc/products/t-eth-elite-1
#
substitutions:
  sd_clk_pin: GPIO10
  sd_cmd_pin: GPIO11
  sd_data0_pin: GPIO09
  #sd_data1_pin: GPIO13
  #sd_data2_pin: GPIO15
  sd_data3_pin: GPIO12

external_components:
  - source: github://atanasenko/esphome_components
    components: [sdmmc]

sdmmc:
  id: sd_card
  mode_1bit: true
  clk_pin: ${sd_clk_pin}
  cmd_pin: ${sd_cmd_pin}
  data0_pin: ${sd_data0_pin}
  #data1_pin: ${sd_data1_pin}
  #data2_pin: ${sd_data2_pin}
  #data3_pin: ${sd_data3_pin}

web_server:
  sorting_groups:
    - id: sorting_group_sd
      name: "SD MMC"
      sorting_weight: 97
